#cloud-config
hostname: ${hostname}
manage_etc_hosts: true

users:
  - name: devops
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

ssh_pwauth: true
chpasswd:
  list: |
    devops:devops
  expire: false

timezone: Europe/Warsaw
