---
- hosts: all
  become: yes

  tasks:
    - name: Copy devops-postgres systemd unit
      copy:
        src: /vagrant/others/devops-postgres.service
        dest: /etc/systemd/system/devops-postgres.service
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start devops-postgres service
      systemd:
        name: devops-postgres.service
        enabled: yes
        state: started
